# release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - "PR: chore"
    authors:
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking change
    - title: Deprecating Changes
      labels:
        - deprecation
    - title: New Features
      labels:
        - "PR: feature"
    - title: Bug fixes
      labels:
        - "PR: fix"
    - title: Cleanup ♻️
      labels:
        - "PR: docs"
        - "PR: refactor"
    - title: Reverted changes
      labels:
        - "PR: revert"
    - title: Other Changes
      labels:
        - "*"
