language: node_js
<<<<<<< HEAD
node_js:
- "stable"
sudo: required
dist: trusty
addons:
 apt:
   sources:
     - google-chrome
   packages:
     - google-chrome-stable
=======
matrix:
  include: 
    - os: linux
      dist: trusty
      node_js: stable
      sudo: required
      addons:
        apt:
          packages:
          - google-chrome-stable
    - os: osx
      node_js: stable
      osx_image: xcode8.3
>>>>>>> 4c4cc7bb3b11d0a899730ae8135c0e9b01a5868c

before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
<<<<<<< HEAD
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - set -x
  - npm test

os:
  - linux
=======
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( scripts/setup_linux_env.sh  ) fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( scripts/setup_osx_env.sh ) fi
  - sleep 2 

script:
  - set -x
  - npm test
>>>>>>> 4c4cc7bb3b11d0a899730ae8135c0e9b01a5868c
