language: node_js
node_js:
- "4"
- "stable"
sudo: false
before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library
script:
  ls -l ../closure-library
  ./build.py
