language: node_js
node_js:
- "4"
- "stable"
sudo: required
dist: trusty
before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library
before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
 
addons:
  browserstack:
    username: "qitan1"
    access_key: "zRqN1zfoJ8vzNnfCmZy9"
