language: node_js
node_js:
- "4"
- "stable"
sudo: false
before_install:
- npm install google-closure-library
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library
script:
  ./build.pyaddons:
addons:
  browserstack:
    username: "qitan1"
    access_key: "zRqN1zfoJ8vzNnfCmZy9"
