on:
  pull_request:
    types: [review_requested]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Check Out Blockly
      uses: actions/checkout@v2

    - name: Assign Reviewer
      uses: actions/github-script@v5
      with:
        script: |
          const script = require('./.github/actions/assign_reviewers.js')
          script({github, context, core})
