# This workflow will do a clean install, start the selenium server, and run
# all of our tests.

name: Node.js CI

on: push

jobs:
  build:
    # TODO (#2114): re-enable osx build.
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm Install
      run: npm install

    - name: Test Setup
      run: |
        export DISPLAY=:99.0
        if [ "${RUNNER_OS}" == "Linux" ]; then ( tests/scripts/setup_linux_env.sh ) fi
        if [ "${RUNNER_OS}" == "macOS" ]; then ( tests/scripts/setup_osx_env.sh ) fi
        sleep 2

    - name: Run
      run: npm run test:run

      env:
        CI: true
