on:
  pull_request:
    types: [review_requested]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Check Out Blockly
      uses: actions/checkout@v2
      with:
        ref: 'test_action' #This checks out the test_action branch.

    - name: Hello world action step
      uses: ./.github/actions/hello_world # This references actions in the same repo.
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
