on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Check Out Blockly
      uses: actions/checkout@v2
      with:
        ref: 'develop'

    - name: Hello world action step
      id: hello
      uses: ./.github/actions/