# This workflow will do a clean install, start the selenium server, and run
# all of our tests.

name: Lint and Run Tests

on: [pull_request]

jobs:
  build:
    # TODO (#2114): re-enable osx build.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Npm Install
      run: npm install

    - name: Linux Test Setup
      if: runner.os == 'Linux'
      run: source ./tests/scripts/setup_linux_env.sh

    - name: MacOS Test Setup
      if: runner.os == 'macOS'
      run: source ./tests/scripts/setup_osx_env.sh

    - name: Mocha Tests
      run: node tests/mocha/run_mocha_tests_in_browser.js

    - name: Generator Tests
      run: source ./tests/scripts/run_generators.sh

      env:
        CI: true
